<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9">
<xsl:output method="html" encoding="UTF-8" indent="yes"/>
<xsl:template match="/">
<html>
<head>
  <title>XML Sitemap — Grow Light DB</title>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 2rem auto; max-width: 800px; padding: 0 1rem; }
    h1 { font-size: 1.5rem; margin-bottom: 0.5rem; }
    p { color: #666; font-size: 0.9rem; margin-bottom: 1.5rem; }
    table { width: 100%; border-collapse: collapse; }
    th { text-align: left; padding: 0.5rem; border-bottom: 2px solid #ddd; font-size: 0.85rem; color: #555; }
    td { padding: 0.5rem; border-bottom: 1px solid #eee; font-size: 0.9rem; }
    tr:hover td { background: #f5f5f5; }
    a { color: #0d3b1e; text-decoration: none; }
    a:hover { text-decoration: underline; }
    .meta { color: #888; font-size: 0.8rem; margin-top: 1rem; }
  </style>
</head>
<body>
  <h1>XML Sitemap — Grow Light DB</h1>
  <p>This XML Sitemap contains <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs.</p>
  <table>
    <tr>
      <th>URL</th>
    </tr>
    <xsl:for-each select="sitemap:urlset/sitemap:url">
      <tr>
        <td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
      </tr>
    </xsl:for-each>
  </table>
  <p class="meta">Generated by Astro Sitemap Plugin</p>
</body>
</html>
</xsl:template>
</xsl:stylesheet>